import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header className="header">
        <div className="header_page_logo">
          <Link href="/">Main Page</Link>
        </div>
      </header>
        {children}</body>
    </html>
  )
}
